### ISSUE TITLE
Empty window

### ISSUE THREAD

**Issue by bezik46** [angular-schule/webcam-viewer#1]
No idea what it is supposed to do, because Chrome console shows only:

Use deviceId query param to request a specific device.
/favicon.ico:1     Failed to load resource: the server responded with a status of 404 ()
[audioinput] : 

[videoinput] : 
angular-schule.github.io/:1 Uncaught (in promise) OverconstrainedError

if I try to access https://angular-schule.github.io/webcam-viewer/

I have only 1 webcam attached

Seb

**Comment by fmalcher** [comment]
Probably fixed! Obviously, the browser doesn't publish any information about the devices as long as we haven't given permission to access the devices. This is good from a privacy perspective!

Now, when no `deviceId` is given, it just takes the first device. After we have given permission, the `deviceId` will be logged to the console.
